language: php
sudo: false
php:
  - 7.0
  - hhvm
install:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - vendor/bin/test-reporter
